2 задание
htmlacademy-htmlcss/1790397-nerds-31 pull request #2
Opened 2021-05-22 10:42 UTC by andrey-torskiy

Разметка главной и внутренней страниц

2021-05-24 22:01 UTC, vladpovelitsa requested changes
Привет, спасибо, что быстро прислал д/з :)

Обрати внимание на пару моментов
---Б15. Единообразное написание и форматирование кода в HTML, CSS и JavaScript
у тебя разное форматирование в каталоге и на главноq, приведи, пожалуйста к единому виду. Для этого можно использовать prittier (для vs code) или аналоги для твоего редактора кода

есть пара правок еще в коде отмеченных, но они не критичны. В целом всё хорошо

2021-05-25 22:04 UTC, vladpovelitsa requested changes
Почти всё супер, остались два небольших момента :)

2021-05-26 19:15 UTC, andrey-torskiy commented on catalog.html
> +            </p>
Логичнее использовать что? div?

2021-05-30 22:13 UTC, vladpovelitsa approved these changes
По текущему заданию всё ок, Молодец! Когда будешь отправлять д/з с графикой пройдись по альтам у картинок, "серая полоска с тремя белыми кругами" - так себе описание)) альт нужен либо для тех, у кого не загружаются картинки, либо для людей с плохим зрением, либо для поисковиков, поэтому они должны нески какой-то смысла типа "Шаблон сайта Х" или что-то в таком духе

2021-05-30 22:13 UTC, merged